### ISSUE TITLE
errors in Chrome console: plugin don't seem to be running

### ISSUE THREAD

**Issue by FabriceNeyret** [jared-hughes/DesModder#49] opened 2021-04-18 17:11 UTC
script.js:336 Uncaught (in promise) TypeError: Cannot read property 'controller' of undefined
    at Object.find_replace_onEnable [as onEnable] (chrome-extension://eclmfdfimjhkmjglgdldedokjaemjfjp/script.js:336)
    at Controller_Controller.enablePlugin (chrome-extension://eclmfdfimjhkmjglgdldedokjaemjfjp/script.js:455)
    at Controller_Controller._registerPlugin (chrome-extension://eclmfdfimjhkmjglgdldedokjaemjfjp/script.js:414)
    at Controller_Controller.registerPlugin (chrome-extension://eclmfdfimjhkmjglgdldedokjaemjfjp/script.js:421)
    at chrome-extension://eclmfdfimjhkmjglgdldedokjaemjfjp/script.js:618
    at Array.forEach (<anonymous>)
    at chrome-extension://eclmfdfimjhkmjglgdldedokjaemjfjp/script.js:617

script.js:518 Uncaught (in promise) TypeError: Cannot read property 'controller' of undefined
    at MenuContainer.template (chrome-extension://eclmfdfimjhkmjglgdldedokjaemjfjp/script.js:518)
    at MenuContainer.e._callTemplate (calculator_desktop-4e0cba7de6873846b3e096379d7004311edd68f3.js:320)
    at new e (calculator_desktop-4e0cba7de6873846b3e096379d7004311edd68f3.js:320)
    at new MenuContainer (chrome-extension://eclmfdfimjhkmjglgdldedokjaemjfjp/script.js:508)
    at Object.mountToNode (calculator_desktop-4e0cba7de6873846b3e096379d7004311edd68f3.js:317)
    at View_View.<anonymous> (chrome-extension://eclmfdfimjhkmjglgdldedokjaemjfjp/script.js:591)
    at Generator.next (<anonymous>)
    at fulfilled (chrome-extension://eclmfdfimjhkmjglgdldedokjaemjfjp/script.js:568)

**Comment by jared-hughes** [comment] 2021-04-18 20:56
Duplicate of #12

**Closed by jared-hughes** 2021-04-18 20:56 UTC
